### ISSUE TITLE
Unexpected results for scene intersection.

### ISSUE THREAD

**Issue by HTDerekLiu** [rohan-sawhney/fcpw#14]
Hi Rohan,

It is me again! I found that some queries for `scene.intersect` gave me unexpected results. In this example, I created two rays shooting from one side of the cube (yellow points) to the other side (purple points):
<img width="563" alt="Screenshot 2024-10-18 at 4 25 40 PM" src="https://github.com/user-attachments/assets/2d979e76-eeee-4dc6-9d74-82f025f8d14b">
But one of them (upper pair) returns a hit, the other one (bottom pair) does not. I wonder whether you know where I may do wrong? 

I extracted a self-contained script here for your reference 
```
import fcpw
import polyscope as ps
import numpy as np

V = np.array([[ 1.6,  1.6,  1.6],
    [14.4,  1.6,  1.6],
    [ 1.6, 14.4,  1.6],
    [14.4, 14.4,  1.6],
    [ 1.6,  1.6, 14.4],
    [14.4,  1.6, 14.4],
    [ 1.6, 14.4, 14.4],
    [14.4, 14.4, 14.4]])
F = np.array([[2, 1, 0],
        [1, 2, 3],
        [4, 2, 0],
        [2, 4, 6],
        [1, 4, 0],
        [4, 1, 5],
        [6, 5, 7],
        [5, 6, 4],
        [3, 6, 7],
        [6, 3, 2],
        [5, 3, 7],
        [3, 5, 1]])

scene = fcpw.scene_3D()
scene.set_object_count(1)
scene.set_object_vertices(V, 0)
scene.set_object_triangles(F, 0)
aggregate_type = fcpw.aggregate_type.bvh_surface_area
build_vectorized_bvh = True
scene.build(aggregate_type, build_vectorized_bvh)

# ray casting 
origins = np.array([[1, 8, 11.5], 
                    [1, 4.5, 11.5]], dtype=float)
dirs = np.array([[1., 0, 0], 
                 [1., 0, 0]], dtype=float)
distance_bounds = np.array([2.0, 2.0], dtype=float)

interactions = fcpw.interaction_3D_list()
scene.intersect(origins, dirs, distance_bounds, interactions, False)

print(interactions[0].primitive_index)
print(interactions[1].primitive_index)

ps.init()
ps.register_surface_mesh("mesh", V, F)
ps.register_point_cloud("origin", origins)
ps.register_point_cloud("end point", origins + dirs * distance_bounds[:,None])
ps.show()
```

**Comment by rohan-sawhney** [comment]
Thanks for reporting this! Seems to be a precision issue, I'll debug it tomorrow :)

**Comment by rohan-sawhney** [comment]
@HTDerekLiu I looked into this and confirmed it is indeed a floating point precision issue happening with the triangle-ray intersection test here: https://github.com/rohan-sawhney/fcpw/blob/346ea475a554083eb8b87f6bbd1b83a1fa1f71c8/include/fcpw/geometry/triangles.inl#L244
As mentioned above, the intersection point should lie along the shared edge between the two nearest triangles (see screenshot below). In this case, the variable `w` should equal `0` in exact precision, but ends up being very very small negative number.

In your test script, the ray-intersection test returns the correct result if you perturb `4.5` even slightly to `4.5000001` or `4.499999` in `origins = np.array([[1, 8, 11.5], [1, 4.5, 11.5]], dtype=float)`:
![Screenshot_2024-10-19_11-36-26](https://github.com/user-attachments/assets/5f455daf-9a6d-46e0-a20e-cc61f63c01a7)

So what should we do about this?

First, this type of ray miss should happen rarely for any rays/geometry in general position. Any other BVH library will likely face similar precision issues, since FCPW's implementation exactly matches the standard [Möller–Trumbore](https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm) test.

I'm a little hesitant about introducing further epsilon checks in the triangle-ray intersection test, since that might introduce its own issues if we overfit to this test case. Thoughts?

**Comment by HTDerekLiu** [comment]
Thanks for the quick response and looking into this issue. What you described makes sense. Introducing further epsilon checks may lead to new issues in other applications. Also once we know that the issue is floating point, it is an easy fix on my end to just shoot a few perturbed rays. 

A proper fix may requite something like [Indirect Predicates](https://www.sciencedirect.com/science/article/abs/pii/S001044852030049X?via%3Dihub), but that requires way more efforts to incorporate. 

I have to say this is one of the most performant and user-friendly libraries for closest points and ray casting! Thanks again for releasing it :)

**Comment by rohan-sawhney** [comment]
Great, feel to report more issues if/as you encounter them. Always looking for ways to improve the library :)
